### PR TITLE
Adding deployment with Fabric (http://www.fabfile.org/) for Ubuntu 14.04 servers

### PR DESCRIPTION
**Pull request by arsenyinfo**
Adding deployment with Fabric (http://www.fabfile.org/) for Ubuntu 14.04 servers

### CODE REVIEW

**Comment by arogozhnikov** [comment]
Hi, Arseniy. Thanks for contribution!

I never used fabric, so I decided to try it and install rep in fresh ubuntu docker container using your script.
I believe, there are several missing steps:

* one needs to install `pip`, `git`, `wget` on home system first, so better add this (this may be a container problem). 
* Then `fabtools` requires (but not installs!) `pycrypto` and `ecdsa`.

Also I had to add 'libffi-dev' in dependencies, otherwise build failed during compilation.

For testing please use `nosetests tests`, because `python tests/test_folding.py` will do nothing...
Tests of rep are __very__ slow, I'll have to introduce some faster testing before, I'd not recommend run testing on each build unless explicitly said.

Could you fix this and test result in your environment?

**Comment by arsenyinfo** [comment]
Alex, thanks for the comments. I'll test it with fresh host machine and nosetests.

**Comment by arsenyinfo** [comment]
Alex, are all the tests currently working correctly? I faced this result:

`Ran 55 tests in 742.511s
FAILED (errors=10, failures=3)`

and I wanted to check if the failures are caused by incorrect installation or tests are just slightly outdated?

**Comment by arogozhnikov** [comment]
@arsenyinfo
Some of neurolab tests normally fail (we can't change anything there, this is knownfail)

Also, due to many changes in theanets and its dependencies, I would expect most or all of it's tests to fail (unfortunately, thanets' author keeps changing interface all the time :/ ). 

Everything else should be fine.

**Comment by tata-antares** [comment]
Hi @arsenyinfo!

Can you send what tests are failed? I will check, if some problems exist with them.

At this moment two tests from `test_theanets`: `test_theanets_partial_fit` and `test_theanets_reproducibility` should fail.

**Comment by arsenyinfo** [comment]
Please see https://gist.github.com/arsenyinfo/4281295f4157234007e5

**Comment by tata-antares** [comment]
These tests should be ok.

That is why, can you provide `root_numpy` version, `xgboost` version in your system?
And also log of command
```
$root
```

**Comment by tata-antares** [comment]
About matplotlib error, try to do this 

```
$export DISPLAY=localhost:0
```
before running tests (http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined)

**Comment by arogozhnikov** [comment]
Huh, failed what I didn't expect to fail. 

As for DISPLAY, I believe that this is conflict of global exports for ROOT (which uses DISPLAY=:0) and matplotlib, which is calling tkinter, which also uses DISPLAY.

**Comment by arogozhnikov** [comment]
That's what I expect to fail at the moment and instructions needed to fight most problems with configuration:

https://travis-ci.org/arogozhnikov/rep/jobs/86099983

**Comment by arogozhnikov** [comment]
Installation procedure was completely changed (we still have standard deployment procedure)

**Pull request closed without merging**
